### ISSUE TITLE
While login i am getting transition superseded error

### ISSUE THREAD

**Issue by TheNuttyMaker** [gothinkster/angularfire-slack#1]
I have completed the tutorial, but when I login or register I am getting transition superseded error. Also because of this, the application is not able to fetch channels, gravatar, and online people. And after login when I reload the application then it works fine without any errors. I am using angular v1.6.1 and angular-ui-router v0.3.2.
I also pulled the latest code in branch 01 and still facing the same issue.

Below are the stack traces

- `angular.js:14328 Error: transition superseded
    at $StateProvider.$get (http://localhost:4000/bower_components/angular-ui-router/release/angular-ui-router.js:2909:37)
    at Object.invoke (http://localhost:4000/bower_components/angular/angular.js:4842:19)
    at http://localhost:4000/bower_components/angular/angular.js:4636:37
    at Object.getService [as get] (http://localhost:4000/bower_components/angular/angular.js:4783:32)
    at http://localhost:4000/bower_components/angular-ui-router/release/angular-ui-router.js:3696:17
    at Object.invoke (http://localhost:4000/bower_components/angular/angular.js:4842:19)
    at http://localhost:4000/bower_components/angular/angular.js:4645:62
    at forEach (http://localhost:4000/bower_components/angular/angular.js:357:20)
    at createInjector (http://localhost:4000/bower_components/angular/angular.js:4645:3)
    at doBootstrap (http://localhost:4000/bower_components/angular/angular.js:1838:20) Possibly unhandled rejection: {}
(anonymous) @ angular.js:14328
(anonymous) @ angular.js:10837
processChecks @ angular.js:16674
$eval @ angular.js:17972
$digest @ angular.js:17786
(anonymous) @ angular.js:18011
completeOutstandingRequest @ angular.js:6111
(anonymous) @ angular.js:6390
`
- `angular.js:14328 Error: [$interpolate:interr] Can't interpolate: {{ channelsCtrl.getGravatar(channelsCtrl.profile.$id) }}
TypeError: Cannot read property 'emailHash' of undefined
http://errors.angularjs.org/1.6.1/$interpolate/interr?p0=%7B%7B%20channelsC…&p1=TypeError%3A%20Cannot%20read%20property%20'emailHash'%20of%20undefined
    at angular.js:68
    at Function.$interpolateMinErr.interr (angular.js:12487)
    at interpolationFn (angular.js:12800)
    at Object.attrInterpolatePreLinkFn (angular.js:10143)
    at angular.js:1291
    at invokeLinkFn (angular.js:10252)
    at nodeLinkFn (angular.js:9618)
    at compositeLinkFn (angular.js:8881)
    at compositeLinkFn (angular.js:8884)
    at compositeLinkFn (angular.js:8884)
`

- `TypeError: Cannot read property 'emailHash' of undefined
    at Object.getGravatar (users.service.js:15)
    at fn (eval at compile (angular.js:1), <anonymous>:4:356)
    at expressionInputWatch (angular.js:16157)
    at Scope.$digest (angular.js:17806)
    at angular.js:18011
    at completeOutstandingRequest (angular.js:6111)
    at angular.js:6390
`

**Comment by jonathanarbely** [comment]
Hey, if you have question, I would recommend the [official Slack channel](https://thinksterpro.slack.com/) to you (pro subscription required). If you don't have access, then I'd recommend checking your Firebase .config object. If that doesn't help either, try to carefully read through the single steps of the tutorial again. Most times, it's just a simple typo. Because it seems like you're missing a character somewhere.

You might also want to take a look [at this](https://github.com/mattlewis92/angular-bluebird-promises/issues/11).

**Comment by Abby3017** [comment]
Hey, I was also facing this problem. I upgraded my ui-router to 0.4.2 . Then it worked fine
